In [31]:
import numpy as np
from scipy import ndimage

with open("../data/day11test0.txt", "r") as f:
    D = np.genfromtxt(f, delimiter=1, dtype=int)

D

array([[1, 1, 1, 1, 1],
       [1, 9, 9, 9, 1],
       [1, 9, 1, 9, 1],
       [1, 9, 9, 9, 1],
       [1, 1, 1, 1, 1]])

In [44]:
# Puzzle 1
# https://scipy-lectures.org/advanced/image_processing/

def do_step(A):

    # Add 1 to all
    A1 = A + 1

    # Initialize array to store which have flashed
    has_flashed = np.zeros_like(A1)

    # Find which to flash
    flash = A1 > 9

    #while np.any(flash):
    for n in range(1):
        # Find which to increase
        # wrong, find a way to add all binary dilations
        # convolution better option
        print(flash.astype(int))
        to_increase = ndimage.grey_dilation(flash.astype(int), structure=np.ones([3, 3], dtype=int))
        print(to_increase.astype(int))
        to_increase = to_increase & ~flash & ~has_flashed

        # Store all the flashed
        has_flashed |= flash

        # Increase 1 around flashes
        A1 += to_increase

    # Reset all flashed to 0
    A1[has_flashed] = 0

    return A1

A = D.copy() + 1
do_step(A)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 3, 11,  3, 11,  3],
       [ 3, 11, 11, 11,  3],
       [ 3,  3,  3,  3,  3]])