In [8]:
import numpy as np

# Load data
with open("../data/day4.txt", "r") as f:
    input = f.read()

data = input.split("\n\n")
number_list = [int(number) for number in data.pop(0).split(",")]

In [13]:
boards = [np.genfromtxt(board.split("\n"), dtype=int, delimiter=3) for board in data] # needs a file or list
boards[0:3]

[array([[48, 69, 68, 49, 13],
        [25, 14, 30, 74, 89],
        [16, 38, 19, 24, 29],
        [56, 97, 50, 65, 79],
        [57, 52,  5, 27, 76]]),
 array([[65, 69, 73, 60, 66],
        [79, 23, 95, 32, 56],
        [36, 51, 26,  1, 28],
        [76,  9,  3, 71, 77],
        [41, 15, 61, 68, 14]]),
 array([[77, 86, 11, 96, 50],
        [64, 35, 76, 14,  5],
        [31, 20, 53, 84, 66],
        [83, 40,  1, 28, 79],
        [15, 74, 92, 65, 39]])]

In [101]:
# Puzzle 1
boards_dict = {i:(board, np.zeros_like(boards[0], dtype=bool)) for i, board in enumerate(boards)}

bingo = False
for number in number_list:
    for key, (board, progress) in boards_dict.items():
        new_progress = progress | (board == number)
        boards_dict[key] = (board, new_progress) # not ideal, have to write board again

        # Check if board is complete
        bingo = new_progress.all(axis=0).any() | new_progress.all(axis=1).any()
        if bingo:
            break
    if bingo:
        break

print(board)
print(number * np.sum(board * ~new_progress))

[[32 81 21 11 31]
 [30 56  3 25 18]
 [80 96 20 65 71]
 [41 67 22 97 10]
 [93 68 17 13  1]]
16674


In [102]:
# Puzzle 2

# Ugly but works

boards_dict = {i:(board, np.zeros_like(boards[0], dtype=bool)) for i, board in enumerate(boards)}

bingo = False
for number in number_list:
    to_pop = []
    for key, (board, progress) in boards_dict.items():
        new_progress = progress | (board == number)
        boards_dict[key] = (board, new_progress) # not ideal, have to write board again

        # Check if board is complete
        bingo = new_progress.all(axis=0).any() | new_progress.all(axis=1).any()
        if bingo:
            to_pop.append(key)
    for p in to_pop:
        boards_dict.pop(p)
        if len(boards_dict) == 0:
            print(number)
            print(board)
            print(number * np.sum(board * ~new_progress))



25
[[ 1 27 74 89  4]
 [29  9 78 48 54]
 [10 38 13 40 49]
 [71 73 79 77 17]
 [25 22 91 20  2]]
7075
