In [124]:
import numpy as np

# Load data
with open("../data/day5test.txt", "r") as f:
    input = f.read()

data = input.split("\n")
lines = [[int(c) for s in line.split(" -> ") for c in s.split(",")] for line in data]
lines[0:15]


[[0, 9, 5, 9],
 [8, 0, 0, 8],
 [9, 4, 3, 4],
 [2, 2, 2, 1],
 [7, 0, 7, 4],
 [6, 4, 2, 0],
 [0, 9, 2, 9],
 [3, 4, 1, 4],
 [0, 0, 8, 8],
 [5, 5, 8, 2]]

In [125]:
N = max([max(line) for line in lines])

In [126]:
# Puzzle 1
A = np.zeros((N+1, N+1))

for line in lines:
    x1, y1, x2, y2 = line
    if x1 == x2:
        y1, y2 = np.sort([y1, y2])
        A[y1:(y2+1), x1] += 1
    if y1 == y2:
        x1, x2 = np.sort([x1, x2])
        A[y1, x1:(x2+1)] += 1
print(A)
np.sum(A >= 2)


[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 1. 2. 1. 1. 1. 2. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 1. 1. 1. 0. 0. 0. 0.]]


5

In [130]:
# Puzzle 2

A = np.zeros((N+1, N+1))

for line in lines:
    x1, y1, x2, y2 = line
    if x1 == x2:
        y1, y2 = np.sort([y1, y2])
        A[y1:(y2+1), x1] += 1
    if y1 == y2:
        x1, x2 = np.sort([x1, x2])
        A[y1, x1:(x2+1)] += 1
    
    if x1 != x2 and y1 != y2:
        dir_x = 2*(x2>x1)-1
        dir_y = 2*(y2>y1)-1
        for x, y in zip(range(x1, x2+dir_x, dir_x), range(y1, y2+dir_y, dir_y)):
            A[y, x] += 1

#print(A)
np.sum(A >= 2)

12