In [14]:
import numpy as np

# Load data
with open("../data/day5.txt", "r") as f:
    input = f.read()

data = input.split("\n")
lines = [[int(c) for s in line.split(" -> ") for c in s.split(",")] for line in data]
lines[0:15]

[[556, 286, 341, 71],
 [337, 201, 782, 646],
 [786, 780, 117, 111],
 [977, 864, 199, 86],
 [544, 127, 544, 144],
 [539, 471, 539, 972],
 [364, 765, 364, 285],
 [282, 325, 892, 935],
 [536, 941, 158, 941],
 [280, 39, 806, 565],
 [168, 662, 363, 857],
 [639, 676, 639, 701],
 [397, 809, 466, 809],
 [716, 118, 625, 209],
 [153, 582, 497, 926]]

In [13]:
# Puzzle 1
N = max([max(line) for line in lines])
A = np.zeros((N+1, N+1))

for line in lines:
    x1, y1, x2, y2 = line
    if x1 == x2:
        y1, y2 = np.sort([y1, y2])
        A[y1:(y2+1), x1] += 1
    if y1 == y2:
        x1, x2 = np.sort([x1, x2])
        A[y1, x1:(x2+1)] += 1
print(A)
np.sum(A >= 2)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 1. 2. 1. 1. 1. 2. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 1. 1. 1. 0. 0. 0. 0.]]


5

In [19]:
# Puzzle 2
N = max([max(line) for line in lines])
A = np.zeros((N+1, N+1))

for line in lines:
    x1, y1, x2, y2 = line
    if x1 == x2:
        y1, y2 = np.sort([y1, y2])
        A[y1:(y2 + 1), x1] += 1
    elif y1 == y2:
        x1, x2 = np.sort([x1, x2])
        A[y1, x1:(x2 + 1)] += 1
    else:
        dir_x = 2*(x2 > x1) - 1
        dir_y = 2*(y2 > y1) - 1
        for x, y in zip(range(x1, x2 + dir_x, dir_x), range(y1, y2 + dir_y, dir_y)):
            A[y, x] += 1

np.sum(A >= 2)

16518